### ISSUE TITLE
Keyword argument is unexpected, but it should be.

### ISSUE THREAD

**Issue by mortilla** [letta-ai/letta#1018]
**Describe the bug**
Then the model replies with a JSON like this:
```
{
  "function": "send_message",
  "params": {
    "inner_thoughts": "Responding to the user's login message by introducing myself.",
    "message": "Hello, Chad! I'm MemGPT, your kind, thoughtful, and inquisitive companion. I'm here to chat and help you with your questions, thoughts, and ideas. Let's have a
great conversation together!"
  }
}
```
MemGPT replies back:
```
{
  "status": "Failed",
  "message": "Error calling function send_message: send_message() got an unexpected keyword argument 'inner_thoughts'",
  "time": "2024-02-16 09:21:31 PM JST+0900"
}
```
However the function descriptions says:
```
send_message:
  description: Sends a message to the human user.
  params:
    inner_thoughts: Deep inner monologue private to you only.
    message: Message contents. All unicode (including emojis) are supported.
```
And therefore the function 
call is correct and should be accepted.

**Please describe your setup**
- [ ] How did you install memgpt?
  - `git clone`
- [ ] Describe your setup
  - Linux
  - Terminal

**Screenshots**
N/A

**Additional context**
[memgpt-prompt.txt](https://github.com/cpacker/MemGPT/files/14311034/memgpt-prompt.txt)

**MemGPT Config**
Please attach your `~/.memgpt/config` file or copy past it below.
[config-redacted.txt](https://github.com/cpacker/MemGPT/files/14311026/config-redacted.txt)

---

If you're not using OpenAI, please provide additional information on your local LLM setup:

**Local LLM details**

If you are trying to run MemGPT with local LLMs, please provide the following information:

- [ ] The exact model you're trying to use (e.g. `dolphin-2.1-mistral-7b.Q6_K.gguf`) miqudev/miqu-1-70b
- [ ] The local LLM backend you are using (web UI? LM Studio?) web UI
- [ ] Your hardware for the local LLM backend (local computer? operating system? remote RunPod?) local Linux
