### ISSUE TITLE
Unexpected code when Attaching MCP Tool

### ISSUE THREAD

**Issue by Jonathan-Harker** [letta-ai/letta#2521]
**Describe the bug**
Tool created with the error 

```python
 raise RuntimeError("Something went wrong - we should never be using the persisted source code for MCP. Please reach out to Letta team")
```

**Please describe your setup**
Docker Compose file with following setup
```
version: "3.8"
services:
  letta:
    image: letta/letta:latest
    ports:
      - "8283:8283"
    volumes:
      - ~/.letta/.persist/pgdata:/var/lib/postgresql/data
      - ./mcp_config.json:/root/.letta/mcp_config.json
    depends_on:
      python-setup:
        condition: service_healthy

  python-setup:
    build: .
    container_name: fast_mpc
    ports:
      - "3000:3000"
      - "5173:5173"
    command: ["mcp", "dev", "main.py"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5173"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
```

A main.py file containing the MCP example code
```python
from mcp.server.fastmcp import FastMCP

mcp = FastMCP("Demo")


@mcp.tool()
def add(a: int, b: int) -> int:
    return a + b


@mcp.resource("greeting://{name}")
def get_greeting(name: str) -> str:
    return f"Hello, {name}!"


if __name__ == "__main__":
    mcp.run()
```

A docker container that acts as the server
```Dockerfile
FROM python:3.11


COPY ./main.py /code/main.py
COPY ./poetry.lock /code/poetry.lock
COPY ./pyproject.toml /code/pyproject.toml

WORKDIR /code

RUN apt-get update && \
    apt-get install -y curl && \
    curl -fsSL https://deb.nodesource.com/setup_18.x | bash - && \
    apt-get install -y nodejs

RUN npm install -g @modelcontextprotocol/inspector@0.6.0

RUN pip install poetry
RUN poetry self add poetry-plugin-export
RUN poetry export -o requirements.txt --without-hashes
RUN poetry config virtualenvs.create false
RUN poetry install
RUN pip install mcp[cli]

CMD ["python", "main.py"]
```
MCP config
```json
{
  "mcpServers": {
    "localTools": {
      "url": "http://python-setup:3000/sse?transportType=stdio&command=python&args=main.py"
    }
  }
}
```

Once running I executed the following script
```python
import os

from letta_client import Letta

os.environ["LETTA_URL"] = "http://localhost:8283"
letta_url = os.getenv("LETTA_URL")
client = Letta(base_url=letta_url)

servers = client.tools.list_mcp_servers()
for server in servers:
    mcp_tools = client.tools.list_mcp_tools_by_server(mcp_server_name=server)
    for tool in mcp_tools:
        tool_res = client.tools.add_mcp_tool(mcp_server_name=server, mcp_tool_name=tool.name)
        res = client.agents.tools.attach(agent_id="agent-2ea95cad-1c00-4930-a8ce-369f10d33f0e", tool_id=tool_res.id)

```
**Screenshots**
<img width="1632" alt="Image" src="https://github.com/user-attachments/assets/43b29574-3bed-4a8b-9714-9ec1c1065778" />
