### ISSUE TITLE
bug: Ollama has KeyError: 'description' in chatml.py

### ISSUE THREAD

**Issue by wsargent** [letta-ai/letta#2588]
**Describe the bug**

```
letta                 | /app/letta/server/server.py:1567: UserWarning: Token streaming is only supported for models with type openai or anthropic or deepseek in the model_endpoint: agent has endpoint type ollama and http://host.docker.internal:11434/. Setting stream_tokens to False.
letta                 |   warnings.warn(
letta                 | 'description'
letta                 | Letta.letta.agent - ERROR - step() failed
letta                 | messages = [Message(created_by_id=None, last_updated_by_id=None, created_at=datetime.datetime(2025, 4, 25, 2, 20, 21, 939672, tzinfo=datetime.timezone.utc), updated_at=None, id='message-1baba3f7-c0a0-4e1e-8eaf-e668761b3eb2', organization_id=None, agent_id='agent-f6e3c998-3793-4092-99c6-031271e51968', model=None, role=<MessageRole.user: 'user'>, content=[TextContent(type=<MessageContentType.text: 'text'>, text='{\n  "type": "user_message",\n  "message": "hello",\n  "time": "2025-04-25 02:20:21 AM UTC+0000"\n}')], name=None, tool_calls=None, tool_call_id=None, step_id=None, otid='5ff373bb-842a-4021-b20f-e2dac77a4782', tool_returns=None, group_id=None, sender_id=None)]
letta                 | error = Failed to convert ChatCompletion messages into prompt string with wrapper <letta.local_llm.llm_chat_completion_wrappers.chatml.ChatMLInnerMonologueWrapper object at 0xffff88ff6110> - error: 'description'
letta                 | Letta.letta.agent - ERROR - step() failed with an unrecognized exception: 'Failed to convert ChatCompletion messages into prompt string with wrapper <letta.local_llm.llm_chat_completion_wrappers.chatml.ChatMLInnerMonologueWrapper object at 0xffff88ff6110> - error: 'description''
letta                 | Traceback (most recent call last):
letta                 |   File "/app/letta/local_llm/chat_completion_proxy.py", line 132, in get_chat_completion
letta                 |     prompt = llm_wrapper.chat_completion_to_prompt(
letta                 |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
letta                 |   File "/app/letta/local_llm/llm_chat_completion_wrappers/chatml.py", line 200, in chat_completion_to_prompt
letta                 |     system_block = self._compile_system_message(
letta                 |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
letta                 |   File "/app/letta/local_llm/llm_chat_completion_wrappers/chatml.py", line 108, in _compile_system_message
letta                 |     prompt += self._compile_function_block(functions)
letta                 |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
letta                 |   File "/app/letta/local_llm/llm_chat_completion_wrappers/chatml.py", line 93, in _compile_function_block
letta                 |     prompt += f"\n{self._compile_function_description(function_dict)}"
letta                 |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
letta                 |   File "/app/letta/local_llm/llm_chat_completion_wrappers/chatml.py", line 81, in _compile_function_description
letta                 |     func_str += f"\n    {param_k}: {param_v['description']}"
letta                 |                                     ~~~~~~~^^^^^^^^^^^^^^^
letta                 | KeyError: 'description'
```

**Please describe your setup**
- [X] How are you running Letta?  
  - Docker 0.7.3
- [X] Describe your setup
  - MacOS 15.4

```
  # Letta is an agent building framework with built-in memory/vectordb support.
  # https://docs.letta.com/quickstart/docker
  letta:
    image: letta/letta:0.7.3
    container_name: letta
    ports:
      - 8283:8283
    volumes:
      # Mount the MCP configuration file (this points to Hayhooks)
      - ./letta_mcp_config.json:/root/.letta/mcp_config.json
    environment:
      # https://docs.letta.com/guides/server/docker#setting-environment-variables
      ANTHROPIC_API_KEY: $ANTHROPIC_API_KEY
      GEMINI_API_KEY: $GEMINI_API_KEY
      # Adding Ollama just in case it's running
      OLLAMA_BASE_URL: http://host.docker.internal:11434/
    restart: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:8283/v1/health/"]
      interval: 5s
      timeout: 5s
      retries: 18
      start_period: 1s
```

---

If you're not using OpenAI, please provide additional information on your local LLM setup:

**Local LLM details**

If you are trying to run Letta with local LLMs, please provide the following information:

- [X] The exact model you're trying to use (e.g. `dolphin-2.1-mistral-7b.Q6_K.gguf`)

gemma3:12b-it-qat

- [X] The local LLM backend you are using (web UI? LM Studio?)

Direct against Letta Desktop 0.7.0

- [ ] Your hardware for the local LLM backend (local computer? operating system? remote RunPod?)

Macbook Pro M3.
