### ISSUE TITLE
Error When Using Qwen3-8B-AWQ Model (VLLM) with MCP Server and Tools Attached

### ISSUE THREAD

**Issue by redtmt2** [letta-ai/letta#2639]
**Describe the bug**
- When connecting to the MCP server (SSE) with tools attached, selecting the model vllm/Qwen/Qwen3-8B-AWQ results in the error:
`Caught unexpected Exception: Failed to convert ChatCompletion messages into prompt string with wrapper <letta.local_llm.llm_chat_completion_wrappers.chatml.ChatMLInnerMonologueWrapper object at 0xffff882a3cd0> - error: 'description'`
- For other providers such as OpenAI, Groq, and Gemini, the MCP tools still work normally.
- Normally work with Qwen model when detach tools from MCP server.

**Please describe your setup**
- [ ] How are you running Letta: Docker 
- [ ] Describe your setup
  - What's your OS (Windows/MacOS/Linux): MacOS
  - What is your `docker run ...` command (if applicable): docker compose up
```
services:
  letta:
    image: letta/letta:0.7.16
    container_name: letta_service
    ports:
      - "8283:8283"
    volumes:
      - ~/.letta/.persist/pgdata:/var/lib/postgresql/data
    env_file:
      - ~/Working/environments/helpbot/.env
    restart: unless-stopped
```

**Screenshots**
![Image](https://github.com/user-attachments/assets/8e628bc4-ac67-4a1d-813b-4d4651772a46)

**Additional context**
- What model you are using: vllm/Qwen/Qwen3-8B-AWQ

**Agent File (optional)**
Please attach your `.af` file, as this helps with reproducing issues. 

---

If you're not using OpenAI, please provide additional information on your local LLM setup:

**Local LLM details**

If you are trying to run Letta with local LLMs, please provide the following information:

- [ ] The exact model you're trying to use: Qwen/Qwen3-8B-AWQ
- [ ] The local LLM backend you are using: vLLM
- [ ] Your hardware for the local LLM backend: local computer
