### ISSUE TITLE
vLLM model not registered with Letta server

### ISSUE THREAD

**Issue by andreea-anghel** [letta-ai/letta#2681]
I'm running `docker compose -f docker-compose-vllm.yaml up` after properly setting the vllm model name and hugging face token. The two containers letta (localhost:8283) and vllm(localhost:8000) are successfully created. However when I run the letta-client to show the registered LLM configs:

```
from letta_client import CreateBlock, Letta, MessageCreate
client = Letta(base_url="http://localhost:8283")
llm_configs = client.models.list()
print(f"Available LLM configs: {llm_configs}")
```
I only see the default letta-free model
```
Available LLM configs: [LlmConfig(model='letta-free', model_endpoint_type='openai', model_endpoint='https://inference.letta.com', provider_name='letta', provider_category='base', model_wrapper=None, context_window=8192, put_inner_thoughts_in_kwargs=True, handle='letta/letta-free', temperature=0.7, max_tokens=4096, enable_reasoner=False, reasoning_effort=None, max_reasoning_tokens=0)]
```

Is this output expected? If I run `curl http://localhost:8000/v1/models` from the host, I do see the right vLLM model. However the letta server does not seem to be able to use it.

Any help is appreciated. Thanks!

**Comment by thongtruong2k1** [comment]
Hi, 
I think u miss VLLM_API_BASE param in your .env file.
For more infomration, check https://docs.letta.com/guides/server/providers/vllm.
Hop this help.

**Comment by sarahwooders** [comment]
Hi thanks for reporting this - we are looking into it!

**Comment by andreea-anghel** [comment]
I'd like to add that 1. the VLLM_BASE_API is correctly set up in the docker compose yaml file and 2. I had to create an agent with the vLLM llm_config to have the agent use that vLLM model.

**Comment by fruworg** [comment]
> Hi thanks for reporting this - we are looking into it!

hi, @sarahwooders, i have the same problem

`compose.yaml`:
```
services:
  letta:
    image: letta/letta:0.11.7
    container_name: letta
    restart: unless-stopped
    ports:
      - "8283:8283"
    environment:
      - LETTA_LLM_ENDPOINT=http://vllm:8000
      - LETTA_LLM_ENDPOINT_TYPE=vllm
      - LETTA_LLM_MODEL=soob3123/amoral-gemma3-1B-v2-qat
      - LETTA_LLM_CONTEXT_WINDOW=2048
      - SECURE=true
      - LETTA_SERVER_PASSWORD=<letta-passwd-redacted>
    depends_on:
      - vllm
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  vllm:
    image: vllm/vllm-openai:v0.8.5
    container_name: vllm
    restart: unless-stopped
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - HUGGING_FACE_HUB_TOKEN=<hf-token-redacted>
    volumes:
      - /mnt/data/cache/huggingface:/root/.cache/huggingface
    command: >
      --model soob3123/amoral-gemma3-1B-v2-qat --max_model_len=2048 --tensor-parallel-size=2 --gpu_memory_utilization=0.95
    ipc: host
```

`$ curl -H "Authorization: Bearer <letta-passwd-redacted>" http://localhost:8283/v1/models/ -s | jq`
```
[
  {
    "model": "letta-free",
    "model_endpoint_type": "openai",
    "model_endpoint": "https://inference.letta.com/v1/",
    "provider_name": "letta",
    "provider_category": "base",
    "model_wrapper": null,
    "context_window": 30000,
    "put_inner_thoughts_in_kwargs": true,
    "handle": "letta/letta-free",
    "temperature": 0.7,
    "max_tokens": null,
    "enable_reasoner": true,
    "reasoning_effort": null,
    "max_reasoning_tokens": 0,
    "frequency_penalty": null,
    "compatibility_type": null,
    "verbosity": null,
    "tier": null
  }
]
```

`# docker compose logs vllm`
```
vllm  | INFO:     Started server process [1]
vllm  | INFO:     Waiting for application startup.
vllm  | INFO:     Application startup complete.
```
